<<<<<<< HEAD
CC := gcc
CFLAGS := -std=gnu11 -Wall -Wextra -g -pthread
INCLUDES := -Icode/include -Icode/include/communication -Icode/include/miner -Icode/include/node
LDLIBS := -lcrypto
=======
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28
>>>>>>> Sviluppo-Processo-Miner

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

<<<<<<< HEAD
# I sorgenti ora stanno anche in sottocartelle: diciamo a make dove cercarli
vpath %.c code/src code/src/communication code/src/miner code/src/node

COMMON_OBJS := \
	$(OBJ)/block.o \
	$(OBJ)/protocolSocket.o \
	$(OBJ)/message.o \
	$(OBJ)/childProcess.o \
	$(OBJ)/utils.o
=======
# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
>>>>>>> Sviluppo-Processo-Miner

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

<<<<<<< HEAD
code/blockchain: $(OBJ)/main.o $(OBJ)/repl.o $(COMMON_OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LDLIBS)
=======
# Disable VCS-based implicit rules.
% : RCS/%
>>>>>>> Sviluppo-Processo-Miner

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

<<<<<<< HEAD
$(BIN)/node: $(OBJ)/node.o $(OBJ)/nodeContext.o $(OBJ)/nodeLog.o $(OBJ)/nodeCSV.o $(OBJ)/nodeFIFO.o $(OBJ)/nodeListener.o $(OBJ)/nodeValidation.o $(OBJ)/nodeStatus.o $(COMMON_OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LDLIBS)
=======
# Disable VCS-based implicit rules.
% : s.%
>>>>>>> Sviluppo-Processo-Miner

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

<<<<<<< HEAD
$(OBJ)/%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
=======
#Suppress display of executed commands.
$(VERBOSE).SILENT:
>>>>>>> Sviluppo-Processo-Miner

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio/CMakeFiles" "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blockchain

# Build rule for target.
blockchain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blockchain
.PHONY : blockchain

# fast build rule for target.
blockchain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/build
.PHONY : blockchain/fast

#=============================================================================
# Target rules for targets named miner

# Build rule for target.
miner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miner
.PHONY : miner

# fast build rule for target.
miner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/build
.PHONY : miner/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/build
.PHONY : node/fast

#=============================================================================
# Target rules for targets named ClientsLauncher

# Build rule for target.
ClientsLauncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClientsLauncher
.PHONY : ClientsLauncher

# fast build rule for target.
ClientsLauncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientsLauncher.dir/build.make CMakeFiles/ClientsLauncher.dir/build
.PHONY : ClientsLauncher/fast

#=============================================================================
# Target rules for targets named MinerLauncher

# Build rule for target.
MinerLauncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MinerLauncher
.PHONY : MinerLauncher

# fast build rule for target.
MinerLauncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MinerLauncher.dir/build.make CMakeFiles/MinerLauncher.dir/build
.PHONY : MinerLauncher/fast

code/src/ClientProcess.o: code/src/ClientProcess.c.o
.PHONY : code/src/ClientProcess.o

# target to build an object file
code/src/ClientProcess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/ClientProcess.c.o
.PHONY : code/src/ClientProcess.c.o

code/src/ClientProcess.i: code/src/ClientProcess.c.i
.PHONY : code/src/ClientProcess.i

# target to preprocess a source file
code/src/ClientProcess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/ClientProcess.c.i
.PHONY : code/src/ClientProcess.c.i

code/src/ClientProcess.s: code/src/ClientProcess.c.s
.PHONY : code/src/ClientProcess.s

# target to generate assembly for a file
code/src/ClientProcess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/ClientProcess.c.s
.PHONY : code/src/ClientProcess.c.s

code/src/ClientsLauncher.o: code/src/ClientsLauncher.c.o
.PHONY : code/src/ClientsLauncher.o

# target to build an object file
code/src/ClientsLauncher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientsLauncher.dir/build.make CMakeFiles/ClientsLauncher.dir/code/src/ClientsLauncher.c.o
.PHONY : code/src/ClientsLauncher.c.o

code/src/ClientsLauncher.i: code/src/ClientsLauncher.c.i
.PHONY : code/src/ClientsLauncher.i

# target to preprocess a source file
code/src/ClientsLauncher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientsLauncher.dir/build.make CMakeFiles/ClientsLauncher.dir/code/src/ClientsLauncher.c.i
.PHONY : code/src/ClientsLauncher.c.i

code/src/ClientsLauncher.s: code/src/ClientsLauncher.c.s
.PHONY : code/src/ClientsLauncher.s

# target to generate assembly for a file
code/src/ClientsLauncher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientsLauncher.dir/build.make CMakeFiles/ClientsLauncher.dir/code/src/ClientsLauncher.c.s
.PHONY : code/src/ClientsLauncher.c.s

code/src/MinerLauncher.o: code/src/MinerLauncher.c.o
.PHONY : code/src/MinerLauncher.o

# target to build an object file
code/src/MinerLauncher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MinerLauncher.dir/build.make CMakeFiles/MinerLauncher.dir/code/src/MinerLauncher.c.o
.PHONY : code/src/MinerLauncher.c.o

code/src/MinerLauncher.i: code/src/MinerLauncher.c.i
.PHONY : code/src/MinerLauncher.i

# target to preprocess a source file
code/src/MinerLauncher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MinerLauncher.dir/build.make CMakeFiles/MinerLauncher.dir/code/src/MinerLauncher.c.i
.PHONY : code/src/MinerLauncher.c.i

code/src/MinerLauncher.s: code/src/MinerLauncher.c.s
.PHONY : code/src/MinerLauncher.s

# target to generate assembly for a file
code/src/MinerLauncher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MinerLauncher.dir/build.make CMakeFiles/MinerLauncher.dir/code/src/MinerLauncher.c.s
.PHONY : code/src/MinerLauncher.c.s

code/src/block.o: code/src/block.c.o
.PHONY : code/src/block.o

# target to build an object file
code/src/block.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/block.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/block.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/block.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/block.c.o
.PHONY : code/src/block.c.o

code/src/block.i: code/src/block.c.i
.PHONY : code/src/block.i

# target to preprocess a source file
code/src/block.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/block.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/block.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/block.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/block.c.i
.PHONY : code/src/block.c.i

code/src/block.s: code/src/block.c.s
.PHONY : code/src/block.s

# target to generate assembly for a file
code/src/block.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/block.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/block.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/block.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/block.c.s
.PHONY : code/src/block.c.s

code/src/blocksPool.o: code/src/blocksPool.c.o
.PHONY : code/src/blocksPool.o

# target to build an object file
code/src/blocksPool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/blocksPool.c.o
.PHONY : code/src/blocksPool.c.o

code/src/blocksPool.i: code/src/blocksPool.c.i
.PHONY : code/src/blocksPool.i

# target to preprocess a source file
code/src/blocksPool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/blocksPool.c.i
.PHONY : code/src/blocksPool.c.i

code/src/blocksPool.s: code/src/blocksPool.c.s
.PHONY : code/src/blocksPool.s

# target to generate assembly for a file
code/src/blocksPool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/blocksPool.c.s
.PHONY : code/src/blocksPool.c.s

code/src/childProcess.o: code/src/childProcess.c.o
.PHONY : code/src/childProcess.o

# target to build an object file
code/src/childProcess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/childProcess.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/childProcess.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/childProcess.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/childProcess.c.o
.PHONY : code/src/childProcess.c.o

code/src/childProcess.i: code/src/childProcess.c.i
.PHONY : code/src/childProcess.i

# target to preprocess a source file
code/src/childProcess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/childProcess.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/childProcess.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/childProcess.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/childProcess.c.i
.PHONY : code/src/childProcess.c.i

code/src/childProcess.s: code/src/childProcess.c.s
.PHONY : code/src/childProcess.s

# target to generate assembly for a file
code/src/childProcess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/childProcess.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/childProcess.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/childProcess.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/childProcess.c.s
.PHONY : code/src/childProcess.c.s

code/src/client.o: code/src/client.c.o
.PHONY : code/src/client.o

# target to build an object file
code/src/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/client.c.o
.PHONY : code/src/client.c.o

code/src/client.i: code/src/client.c.i
.PHONY : code/src/client.i

# target to preprocess a source file
code/src/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/client.c.i
.PHONY : code/src/client.c.i

code/src/client.s: code/src/client.c.s
.PHONY : code/src/client.s

# target to generate assembly for a file
code/src/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/client.c.s
.PHONY : code/src/client.c.s

code/src/main.o: code/src/main.c.o
.PHONY : code/src/main.o

# target to build an object file
code/src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/main.c.o
.PHONY : code/src/main.c.o

code/src/main.i: code/src/main.c.i
.PHONY : code/src/main.i

# target to preprocess a source file
code/src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/main.c.i
.PHONY : code/src/main.c.i

code/src/main.s: code/src/main.c.s
.PHONY : code/src/main.s

# target to generate assembly for a file
code/src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/main.c.s
.PHONY : code/src/main.c.s

code/src/message.o: code/src/message.c.o
.PHONY : code/src/message.o

# target to build an object file
code/src/message.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/message.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/message.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/message.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/message.c.o
.PHONY : code/src/message.c.o

code/src/message.i: code/src/message.c.i
.PHONY : code/src/message.i

# target to preprocess a source file
code/src/message.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/message.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/message.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/message.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/message.c.i
.PHONY : code/src/message.c.i

code/src/message.s: code/src/message.c.s
.PHONY : code/src/message.s

# target to generate assembly for a file
code/src/message.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/message.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/message.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/message.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/message.c.s
.PHONY : code/src/message.c.s

code/src/miner.o: code/src/miner.c.o
.PHONY : code/src/miner.o

# target to build an object file
code/src/miner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/miner.c.o
.PHONY : code/src/miner.c.o

code/src/miner.i: code/src/miner.c.i
.PHONY : code/src/miner.i

# target to preprocess a source file
code/src/miner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/miner.c.i
.PHONY : code/src/miner.c.i

code/src/miner.s: code/src/miner.c.s
.PHONY : code/src/miner.s

# target to generate assembly for a file
code/src/miner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/miner.c.s
.PHONY : code/src/miner.c.s

code/src/minerCommunicationProcess.o: code/src/minerCommunicationProcess.c.o
.PHONY : code/src/minerCommunicationProcess.o

# target to build an object file
code/src/minerCommunicationProcess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProcess.c.o
.PHONY : code/src/minerCommunicationProcess.c.o

code/src/minerCommunicationProcess.i: code/src/minerCommunicationProcess.c.i
.PHONY : code/src/minerCommunicationProcess.i

# target to preprocess a source file
code/src/minerCommunicationProcess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProcess.c.i
.PHONY : code/src/minerCommunicationProcess.c.i

code/src/minerCommunicationProcess.s: code/src/minerCommunicationProcess.c.s
.PHONY : code/src/minerCommunicationProcess.s

# target to generate assembly for a file
code/src/minerCommunicationProcess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProcess.c.s
.PHONY : code/src/minerCommunicationProcess.c.s

code/src/minerCommunicationProtocol.o: code/src/minerCommunicationProtocol.c.o
.PHONY : code/src/minerCommunicationProtocol.o

# target to build an object file
code/src/minerCommunicationProtocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProtocol.c.o
.PHONY : code/src/minerCommunicationProtocol.c.o

code/src/minerCommunicationProtocol.i: code/src/minerCommunicationProtocol.c.i
.PHONY : code/src/minerCommunicationProtocol.i

# target to preprocess a source file
code/src/minerCommunicationProtocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProtocol.c.i
.PHONY : code/src/minerCommunicationProtocol.c.i

code/src/minerCommunicationProtocol.s: code/src/minerCommunicationProtocol.c.s
.PHONY : code/src/minerCommunicationProtocol.s

# target to generate assembly for a file
code/src/minerCommunicationProtocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerCommunicationProtocol.c.s
.PHONY : code/src/minerCommunicationProtocol.c.s

code/src/minerFifo.o: code/src/minerFifo.c.o
.PHONY : code/src/minerFifo.o

# target to build an object file
code/src/minerFifo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerFifo.c.o
.PHONY : code/src/minerFifo.c.o

code/src/minerFifo.i: code/src/minerFifo.c.i
.PHONY : code/src/minerFifo.i

# target to preprocess a source file
code/src/minerFifo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerFifo.c.i
.PHONY : code/src/minerFifo.c.i

code/src/minerFifo.s: code/src/minerFifo.c.s
.PHONY : code/src/minerFifo.s

# target to generate assembly for a file
code/src/minerFifo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerFifo.c.s
.PHONY : code/src/minerFifo.c.s

code/src/minerStatus.o: code/src/minerStatus.c.o
.PHONY : code/src/minerStatus.o

# target to build an object file
code/src/minerStatus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerStatus.c.o
.PHONY : code/src/minerStatus.c.o

code/src/minerStatus.i: code/src/minerStatus.c.i
.PHONY : code/src/minerStatus.i

# target to preprocess a source file
code/src/minerStatus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerStatus.c.i
.PHONY : code/src/minerStatus.c.i

code/src/minerStatus.s: code/src/minerStatus.c.s
.PHONY : code/src/minerStatus.s

# target to generate assembly for a file
code/src/minerStatus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerStatus.c.s
.PHONY : code/src/minerStatus.c.s

code/src/minerThread.o: code/src/minerThread.c.o
.PHONY : code/src/minerThread.o

# target to build an object file
code/src/minerThread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerThread.c.o
.PHONY : code/src/minerThread.c.o

code/src/minerThread.i: code/src/minerThread.c.i
.PHONY : code/src/minerThread.i

# target to preprocess a source file
code/src/minerThread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerThread.c.i
.PHONY : code/src/minerThread.c.i

code/src/minerThread.s: code/src/minerThread.c.s
.PHONY : code/src/minerThread.s

# target to generate assembly for a file
code/src/minerThread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/minerThread.c.s
.PHONY : code/src/minerThread.c.s

code/src/node.o: code/src/node.c.o
.PHONY : code/src/node.o

# target to build an object file
code/src/node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/node.c.o
.PHONY : code/src/node.c.o

code/src/node.i: code/src/node.c.i
.PHONY : code/src/node.i

# target to preprocess a source file
code/src/node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/node.c.i
.PHONY : code/src/node.c.i

code/src/node.s: code/src/node.c.s
.PHONY : code/src/node.s

# target to generate assembly for a file
code/src/node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/node.c.s
.PHONY : code/src/node.c.s

code/src/nodeStatus.o: code/src/nodeStatus.c.o
.PHONY : code/src/nodeStatus.o

# target to build an object file
code/src/nodeStatus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/nodeStatus.c.o
.PHONY : code/src/nodeStatus.c.o

code/src/nodeStatus.i: code/src/nodeStatus.c.i
.PHONY : code/src/nodeStatus.i

# target to preprocess a source file
code/src/nodeStatus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/nodeStatus.c.i
.PHONY : code/src/nodeStatus.c.i

code/src/nodeStatus.s: code/src/nodeStatus.c.s
.PHONY : code/src/nodeStatus.s

# target to generate assembly for a file
code/src/nodeStatus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/nodeStatus.c.s
.PHONY : code/src/nodeStatus.c.s

code/src/protocolSocket.o: code/src/protocolSocket.c.o
.PHONY : code/src/protocolSocket.o

# target to build an object file
code/src/protocolSocket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/protocolSocket.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/protocolSocket.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/protocolSocket.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/protocolSocket.c.o
.PHONY : code/src/protocolSocket.c.o

code/src/protocolSocket.i: code/src/protocolSocket.c.i
.PHONY : code/src/protocolSocket.i

# target to preprocess a source file
code/src/protocolSocket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/protocolSocket.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/protocolSocket.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/protocolSocket.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/protocolSocket.c.i
.PHONY : code/src/protocolSocket.c.i

code/src/protocolSocket.s: code/src/protocolSocket.c.s
.PHONY : code/src/protocolSocket.s

# target to generate assembly for a file
code/src/protocolSocket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/protocolSocket.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/protocolSocket.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/protocolSocket.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/protocolSocket.c.s
.PHONY : code/src/protocolSocket.c.s

code/src/transactionPool.o: code/src/transactionPool.c.o
.PHONY : code/src/transactionPool.o

# target to build an object file
code/src/transactionPool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/transactionPool.c.o
.PHONY : code/src/transactionPool.c.o

code/src/transactionPool.i: code/src/transactionPool.c.i
.PHONY : code/src/transactionPool.i

# target to preprocess a source file
code/src/transactionPool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/transactionPool.c.i
.PHONY : code/src/transactionPool.c.i

code/src/transactionPool.s: code/src/transactionPool.c.s
.PHONY : code/src/transactionPool.s

# target to generate assembly for a file
code/src/transactionPool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/transactionPool.c.s
.PHONY : code/src/transactionPool.c.s

code/src/utils.o: code/src/utils.c.o
.PHONY : code/src/utils.o

# target to build an object file
code/src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/utils.c.o
.PHONY : code/src/utils.c.o

code/src/utils.i: code/src/utils.c.i
.PHONY : code/src/utils.i

# target to preprocess a source file
code/src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/utils.c.i
.PHONY : code/src/utils.c.i

code/src/utils.s: code/src/utils.c.s
.PHONY : code/src/utils.s

# target to generate assembly for a file
code/src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/code/src/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miner.dir/build.make CMakeFiles/miner.dir/code/src/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/code/src/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/code/src/utils.c.s
.PHONY : code/src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ClientsLauncher"
	@echo "... MinerLauncher"
	@echo "... blockchain"
	@echo "... client"
	@echo "... miner"
	@echo "... node"
	@echo "... code/src/ClientProcess.o"
	@echo "... code/src/ClientProcess.i"
	@echo "... code/src/ClientProcess.s"
	@echo "... code/src/ClientsLauncher.o"
	@echo "... code/src/ClientsLauncher.i"
	@echo "... code/src/ClientsLauncher.s"
	@echo "... code/src/MinerLauncher.o"
	@echo "... code/src/MinerLauncher.i"
	@echo "... code/src/MinerLauncher.s"
	@echo "... code/src/block.o"
	@echo "... code/src/block.i"
	@echo "... code/src/block.s"
	@echo "... code/src/blocksPool.o"
	@echo "... code/src/blocksPool.i"
	@echo "... code/src/blocksPool.s"
	@echo "... code/src/childProcess.o"
	@echo "... code/src/childProcess.i"
	@echo "... code/src/childProcess.s"
	@echo "... code/src/client.o"
	@echo "... code/src/client.i"
	@echo "... code/src/client.s"
	@echo "... code/src/main.o"
	@echo "... code/src/main.i"
	@echo "... code/src/main.s"
	@echo "... code/src/message.o"
	@echo "... code/src/message.i"
	@echo "... code/src/message.s"
	@echo "... code/src/miner.o"
	@echo "... code/src/miner.i"
	@echo "... code/src/miner.s"
	@echo "... code/src/minerCommunicationProcess.o"
	@echo "... code/src/minerCommunicationProcess.i"
	@echo "... code/src/minerCommunicationProcess.s"
	@echo "... code/src/minerCommunicationProtocol.o"
	@echo "... code/src/minerCommunicationProtocol.i"
	@echo "... code/src/minerCommunicationProtocol.s"
	@echo "... code/src/minerFifo.o"
	@echo "... code/src/minerFifo.i"
	@echo "... code/src/minerFifo.s"
	@echo "... code/src/minerStatus.o"
	@echo "... code/src/minerStatus.i"
	@echo "... code/src/minerStatus.s"
	@echo "... code/src/minerThread.o"
	@echo "... code/src/minerThread.i"
	@echo "... code/src/minerThread.s"
	@echo "... code/src/node.o"
	@echo "... code/src/node.i"
	@echo "... code/src/node.s"
	@echo "... code/src/nodeStatus.o"
	@echo "... code/src/nodeStatus.i"
	@echo "... code/src/nodeStatus.s"
	@echo "... code/src/protocolSocket.o"
	@echo "... code/src/protocolSocket.i"
	@echo "... code/src/protocolSocket.s"
	@echo "... code/src/transactionPool.o"
	@echo "... code/src/transactionPool.i"
	@echo "... code/src/transactionPool.s"
	@echo "... code/src/utils.o"
	@echo "... code/src/utils.i"
	@echo "... code/src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

