# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio/CMakeFiles" "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/andrea/Documenti/Uni/Secondo Anno/Sistemi_Operativi/Gonzato_Luongo_Griggio/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gonzato_Luongo_Griggio

# Build rule for target.
Gonzato_Luongo_Griggio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Gonzato_Luongo_Griggio
.PHONY : Gonzato_Luongo_Griggio

# fast build rule for target.
Gonzato_Luongo_Griggio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/build
.PHONY : Gonzato_Luongo_Griggio/fast

code/src/block.o: code/src/block.c.o
.PHONY : code/src/block.o

# target to build an object file
code/src/block.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/block.c.o
.PHONY : code/src/block.c.o

code/src/block.i: code/src/block.c.i
.PHONY : code/src/block.i

# target to preprocess a source file
code/src/block.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/block.c.i
.PHONY : code/src/block.c.i

code/src/block.s: code/src/block.c.s
.PHONY : code/src/block.s

# target to generate assembly for a file
code/src/block.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/block.c.s
.PHONY : code/src/block.c.s

code/src/childProcess.o: code/src/childProcess.c.o
.PHONY : code/src/childProcess.o

# target to build an object file
code/src/childProcess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/childProcess.c.o
.PHONY : code/src/childProcess.c.o

code/src/childProcess.i: code/src/childProcess.c.i
.PHONY : code/src/childProcess.i

# target to preprocess a source file
code/src/childProcess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/childProcess.c.i
.PHONY : code/src/childProcess.c.i

code/src/childProcess.s: code/src/childProcess.c.s
.PHONY : code/src/childProcess.s

# target to generate assembly for a file
code/src/childProcess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/childProcess.c.s
.PHONY : code/src/childProcess.c.s

code/src/main.o: code/src/main.c.o
.PHONY : code/src/main.o

# target to build an object file
code/src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/main.c.o
.PHONY : code/src/main.c.o

code/src/main.i: code/src/main.c.i
.PHONY : code/src/main.i

# target to preprocess a source file
code/src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/main.c.i
.PHONY : code/src/main.c.i

code/src/main.s: code/src/main.c.s
.PHONY : code/src/main.s

# target to generate assembly for a file
code/src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gonzato_Luongo_Griggio.dir/build.make CMakeFiles/Gonzato_Luongo_Griggio.dir/code/src/main.c.s
.PHONY : code/src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Gonzato_Luongo_Griggio"
	@echo "... code/src/block.o"
	@echo "... code/src/block.i"
	@echo "... code/src/block.s"
	@echo "... code/src/childProcess.o"
	@echo "... code/src/childProcess.i"
	@echo "... code/src/childProcess.s"
	@echo "... code/src/main.o"
	@echo "... code/src/main.i"
	@echo "... code/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

